server {
    listen       80;
    server_name  localhost;

    # Nginx root maps to the parent folder so it serves index.html
    root   /usr/share/nginx/html;
    index  index.html;

    # Basic setup to correctly serve files
    location / {
        try_files $uri $uri/ =404;
    }

    # Optional: ensure correct MIME types are sent
    include /etc/nginx/mime.types;
}
